#+TITLE: Junwei Wang - Resume

# * Resume

** Profile

I am a Ph.D. in *cryptography*.
My Ph.D. thesis is about *white-box cryptography*.
White-box cryptography is a key means to ensure the security of cryptographic implementations in untrusted computing environments.
It is widely used in *DRM* and *mobile payments*.

I have 7+ years of experience in software development.
I have written code for *cryptography and security*, *big-data processing*, *system administration*, *back-end services*, and *web applications*.
I have a good understanding of software architecture and the way to write clean code.
I have balanced ability to do scientific research and do engineering.

I have several peer-viewed major publications on white-box cryptography and cryptographic implementations.

# My work and research interests are white-box cryptography and privacy-preserving cryptography.
# In particular, I design and/or break white-box implementations for cryptographic primitives deployed in untrusted computation environment;
# And I apply cutting-edge research results in cryptography to enhance the user's privacy and to protect customer's intellectual property.

I was on the program committee of [[https://ches.iacr.org/2022][CHES 2022]], [[https://ches.iacr.org/2022/artifacts.php][CHES 2022 artifact review]], and [[https://ches.iacr.org/2021/artifacts.php][CHES 2021 artifact review]].
I co-organized two editions of white-box competitions: [[https://whibox.io/contests/2021/][WhibOx Contest 2021]] and [[https://whibox.io/contests/2019/][WhibOx Contest 2019]].
I was an [[https://www.ecrypt.eu.org/net/][ECRYPT-NET]] fellow.

** Work Experience

*** Software Security Engineer, [[https://www.apple.com][Apple]]
/November 2021 - today/

Analyzing the security of white-box implementations used in Apple DRM.

*Tools*: C/C++, Python, Shell, Buildbot

*** Cryptography Expert, [[https://cryptoexperts.com][CryptoExperts]], Paris
/April 2017 - November 2021/

CryptoExperts is a service and technology company in cryptography.
I mainly worked on white-box cryptography and privacy-preserving cryptography.

Specifically, I was responsible for
- designing and building white-box implementations for standard cryptographic primitives that pass security evaluation from an accredited security laboratory.
- developing on white-box analytical tools.
- designing and implementing a generic framework to prototype for evolving white-box designs
- designing and developing a web services to automate the generation and delivery of our white-box implementations.
- designing and prototyping privacy-preserving cryptography for our customers in various applications including privacy-preserving machine learning, and private data retrieval, and so on.
- administrating the intranet and cloud services.

*Tools*: AWS, Docker, Python, C, SageMath, Mathematica

*** Software Engineer, [[https://baidu.com][Baidu]], Beijing
/July 2015 - April 2017/

As a member of the Artificial Intelligent Group (AIG), mainly focus on automating the process of generating knowledge graphs data for the Baidu search engine.

Specifically,
- designed and developed a workflow system based on the Apache Airflow project for scheduling, monitoring the process of knowledge graphs with a complex dependency topology.
- developed an adapter system for the compatibility between protocols for batch data and stream data.
- developed a computation framework for batch data.
- developed a data cleaning system based on the OpenRefine project.

*Tools*: Linux, Docker, Java, Python, PHP, Hadoop, HBase, Apache Airflow, OpenRefine

*** Research Intern, [[https://www.riscure.com/][Riscure]], Delft
/April 2018 - July 2018/

Investigated in-depth when and why *differential computation analysis* (DCA) is able to break internally-encoded white-box implementations.
Partial work published in top-tier cryptography conference [[https://tches.iacr.org/index.php/TCHES/issue/view/91][TCHES 2019]].

*Tools*: Probability, Boolean functions theory, algebra.

*** Backend Engineer Intern, [[https://www.eyespage.com/][Eyespage]], Beijing
/December 2014 - May 2015/

- Co-designed the architecture of the back-end system.
- Designed and developed RESTful API design with Python stack.
- Developed a spider to crawl application metadata from Google Play Store by using the Scrapy framework.
- Used ELK stack and Zabbix for monitor, analysis, and operations.

*Tools*: Linux, Python stack, ELK stack, MySQL, Apache Cassandra

*** Operations Engineer Inter, [[https://baidu.com][Baidu]], Beijing
/August 2011 - January 2012/

Using the telemetry data collected by the browser and third-party clients, developed a user-friendly monitoring and early warning system for Baidu's various online services.
Mainly focused on obtaining interesting data from scratch, then processing, storing, and displaying them with charts.

*Tools*: Linux, Python, Shell, PHP, MySQL

** Education

*** Ph.D. in Cryptography, University of Luxembourg / University Paris 8
/April 2017 - June 2020/

My thesis subject is white-box cryptography, which is a particularly challenging research topic, and which has important applications for the industry of secure software.
I quote part of the detailed opinion of the dissertation defense jury in my thesis report.

#+begin_quote
The contributions of Junwei Wang are of both theoretical and practical nature, with on the one hand, the analysis and improvement of white-box attack techniques and countermeasures, and on the other hand, the realization of concrete attacks, notably leading to the break of the winning challenges from the international WhibOx competitions.
The presented work achieves a significant and important step towards the understanding of the practical security of white-box cryptography.

------ Thesis report
#+end_quote

More information on my thesis can be found in [[https://jwa.ng/thesis/][jwa.ng/thesis]].

*** Master in Computer Science, University of Luxembourg / Shandong University
/September 2012 - June 2015/

I successfully defended my master thesis, entitled *Efficient Implementation of High-Order DPA Countermeasures for the AES Using the ARM NEON Instruction Set*, with an /excellent/ mark (18/20).
My work achieved protection against higher-order DPA attacks with a very low penalty factor through a combination of algebraic, algorithmic, and implementation techniques.
The obtained results in my master thesis were published at [[https://www.springer.com/gp/book/9783319167145][CT-RSA 2015]].

*** Bachelor in Software Engineering, Shandong University
/September 2008 - June 2012/, GPA: 89.35/100

I learned the computer science fundamentals, including but not limited to operating system, data structures and algorithms, computer network, compilation theory, etc.
As the graduation project, I implemented the *Ciphertext-Policy Attributed-Based Encryption* (CP-ABE) in Java.
The source code is available at [[https://github.com/junwei-wang/cpabe][junwei-wang/cpabe]].

** Publications

[1] L.Goubin, M.Rivain, **J.Wang**: /Defeating State-of-the-Art White-Box Countermeasures with Advanced Gray-Box Attacks./ IACR TCHES 2020.

[2] L.Goubin, P.Paillier, M.Rivain, **J.Wang**: /How to reveal the secrets of an obscure white-box implementation./ Journal of Cryptographic Engineering 10(1).

[3] M.Rivain, **J.Wang**: /Analysis and Improvement of Differential Computation Attacks against Internally-Encoded White-Box Implementations./ IACR TCHES 2019.

[4] A.Bogdanov, M.Rivain, P.S.Vejre, **J.Wang**: /Higher-Order DCA against Standard Side-Channel Countermeasures./ COSADE 2019: 118-141

[5] **J.Wang**, P.K.Vadnala, J.Großschädl, Q.Xu: /Higher-Order Masking in Practice: A Vector Implementation of Masked AES for ARM NEON./ CT-RSA 2015: 181-198

** Languages

- *English* (work proficiency)
- *Chinese* (mother tongue)
- *French* (A2)

** Contact

- *Email*: [[mailto:me@jwa.ng][me@jwa.ng]] / [[mailto:jwang@mailbox.org][jwang@mailbox.org]]
- *Phone*: +33 (0) 7 69 39 52 85
